Fix Translations & Update Package Lock
cerner/terra-toolkit pull request #215
Opened 2018-12-13 01:05 UTC by emilyrohrbough

### Summary
#### Translations
- Latest updates were exhaustively searching every possible node_module directory instead of the top level which was take a very long time.
- Latest updates passes an array of arrays to the aggragate-messages function when it expected an array of paths. I tried a bunch of ways to test this and cannot find a good way to validate we are passing an array of strings since its modularized and we tested each piece. Ideas?

#### Package-lock
This was updated and the old version still contained lock on uglifyjs-webpack plugin which was pulling in a different major version of cacache (and some others) than what terser-webpack-plugin was specifying. I think this is what was causing the garbage collection issues downstream projects pulling terra-toolkit. This framework branch was updated to use this toolkit branch: https://github.com/cerner/terra-framework/pull/389

I also had to update terra-dev-site's package-lock because it was also pretty dated. We should probably try to update these each release to prevent clashing.

2018-12-13 01:08 UTC, emilyrohrbough commented on scripts/aggregate-translations/aggregate-translations.js
> +  path.resolve(baseDirectory, 'packages', '*', 'node_modules', '*', 'translations'), // package level dependency translations
previously this was `path.resolve(baseDirectory, 'packages', 'terra-*', 'node_modules', 'terra-*', 'translations'),`
https://github.com/cerner/terra-toolkit/pull/205/files#diff-b0cbeddb18aad238c54237791e92c1aaL14

2018-12-13 01:09 UTC, emilyrohrbough commented on scripts/aggregate-translations/aggregate-translations.js
> +  path.resolve(baseDirectory, 'node_modules', '*', 'translations'), // root level dependency translations
previously this was `path.resolve(baseDirectory, 'node_modules', 'terra-*', 'translations'), `
https://github.com/cerner/terra-toolkit/pull/205/files#diff-b0cbeddb18aad238c54237791e92c1aaL12

2018-12-13 01:09 UTC, emilyrohrbough commented on scripts/aggregate-translations/aggregate-translations.js
> -  const translationDirectories = searchPaths.map(searchPath => glob.sync(searchPath));
This was returning an Array of Arrays instead of an Array of path strings

2018-12-13 01:10 UTC, emilyrohrbough commented on tests/jest/aggregate-messages.test.js
> +    const messages = aggregateMessages([], locales);
The aggregateMessages functions doesn't accept a fileSystem parameter so this was dead-test code.

2018-12-13 01:10 UTC, emilyrohrbough commented on tests/jest/aggregate-translations.test.js
> +  `${baseDirectory}/packages/*/node_modules/*/translations`,
Glob expects only `/` for search patterns so we don't need to use device specific path separators here.

2018-12-13 01:32 UTC, bjankord approved these changes

2018-12-13 16:55 UTC, tbiethman approved these changes

2018-12-13 17:39 UTC, tbiethman requested changes
Do we want to add another default search path for dependencies of dependencies inside node_modules (but outside packages?) Would it make sense to even go a layer deeper?

```
path.resolve(baseDirectory, 'node_modules', '*', 'node_modules', '*', 'translations'), // root level dependencies' dependency translations
```

2018-12-13 19:58 UTC, emilyrohrbough commented
@tbiethman We talked, I agree opening this up beyond a single node_modules layer would be good. Are you thinking 3 or 4 layers? I would like to refrain from exhaustively searching every possible directory for translations. I'm thinking
```
default searchPaths = [
  'baseDirectory/translations', 
  'baseDirectory/node_modules/*/translations', 
  'baseDirectory/node_modules/*/node_modules/*/translations', 
  'baseDirectory/node_modules/*/node_modules/*/node_modules/*/translations', 
  'baseDirectory/packages/terra-*/translations',
  'baseDirectory/packages/terra-*/node_modules/*/translations',
  'baseDirectory/packages/terra-*/node_modules/*/node_modules/*/translations',
  'baseDirectory/packages/terra-*/node_modules/*/node_modules/*/node_modules/*/translations',
]
```

2018-12-13 20:12 UTC, bjankord commented
@emilyrohrbough Let's go with 3. We can move to 4 if we need to later on.

2018-12-14 15:48 UTC, emilyrohrbough commented
This is ready for a new review! I realized we were doing too much work that glob will do for us. I have added the following [glob options](https://github.com/isaacs/node-glob#options) to simplify our setup:

- cwd - root dir to start search patterns from
- ignore - the pattern or array of patterns to exclude
- follow - Follow symlinked directories when expanding ** patterns. <-- this will enable local dev of modules that have their own translations

Test this in terra-framework by pulling in an non-mono-repo package that contained translations. Its translations and it's node_module's translations were pulled in while symlinked.

2018-12-14 15:49 UTC, emilyrohrbough commented on scripts/aggregate-translations/aggregate-messages.js
> +const aggregateTranslationMessages = (translationDirectories, locales, fileSystem) => {
Bug fix. This should have been passed down to map the existing fileSystem option

2018-12-14 15:49 UTC, emilyrohrbough commented on scripts/aggregate-translations/aggregate-translations.js
> -const defaultSearchPatterns = baseDirectory => ([
Moved to their own file as these patterns have gotten sorta large

2018-12-14 16:25 UTC, tbiethman approved these changes

2018-12-14 20:50 UTC, ryanthemanuel commented on scripts/aggregate-translations/defaultSearchPatterns.js
> +  /* package level dependency translations up to three levels deep */
Any particular reason to stop at 3?

2018-12-14 20:51 UTC, ryanthemanuel approved these changes

2018-12-14 20:51 UTC, merged