Disabled accessibility tests for clinical-lowlight-theme
cerner/terra-toolkit pull request #352
Opened 2019-11-13 15:01 UTC by avinashg1994

### Summary

Added a check to disable accessibility tests for **clinical-lowlight-theme** to prevent the color contrast violations.

2019-11-13 15:19 UTC, nramamurth commented on src/wdio/services/TerraCommands/accessibility.js
> +  if (theme !== 'clinical-lowlight-theme') {
Is this for short-term or long-term? In either case, I think it is better to have a follow-up issue to remove this check whenever a decision is made to test accessibility in lowlight.

2019-11-13 15:25 UTC, nramamurth commented
@neilpfeiffer, I do not seem to recollect the actual reason — why exactly do we have color contrast issues in Lowlight? Will we go back and _fix_ them in the future?

2019-11-13 16:15 UTC, emilyrohrbough requested changes
Please see the comment left on the issue:
https://github.com/cerner/terra-toolkit/issues/351#issuecomment-553474034

2019-11-14 12:49 UTC, closed without merging

2019-11-14 12:50 UTC, emilyrohrbough commented on src/wdio/services/TerraCommands/determine-test-options.js
> +    ...axeRules && { rules: { ...globalAxeRules, ...axeRules } },
I'm not sure this change is needed. Did the axe tool not properly configure with the root level configuration? Do you have a couple test runs as evidence you can link?